return {
  "harrisoncramer/gitlab.nvim",
  dependencies = {
    "MunifTanjim/nui.nvim",
    "nvim-lua/plenary.nvim",
    "sindrets/diffview.nvim",
    "stevearc/dressing.nvim",
    "nvim-tree/nvim-web-devicons",
  },
  build = function()
    require("gitlab.server").build(true)
  end,
  config = function()
    require("gitlab").setup({
      -- Configuration options
      port = nil, -- The port of the Go server, which runs in the background
      log_path = vim.fn.stdpath("cache") .. "/gitlab.nvim.log",
      config_path = nil, -- Custom path for `.gitlab.nvim` file
      debug = { go_request = false, go_response = false },
      attachment_dir = nil, -- Directory for attachments
      popup = {
        exit = "q",
        perform_action = "<leader>",
        perform_linewise_action = "<leader>",
        width = "40%",
        height = "60%",
        border = "rounded",
        opacity = 1.0,
        comment = nil,
        edit = nil,
        note = nil,
        help = nil,
        pipeline = nil,
        reply = nil,
        squash_message = nil,
      },
      discussion_tree = {
        auto_open = true,
        switch_view = "S",
        default_view = "discussions",
        blacklist = {},
        jump_to_file = "o",
        jump_to_reviewer = "m",
        edit_comment = "e",
        delete_comment = "dd",
        reply = "r",
        toggle_node = "t",
        toggle_all_discussions = "T",
        toggle_resolved_discussions = "R",
        toggle_unresolved_discussions = "U",
        keep_current_open = false,
        position = "left",
        size = "20%",
        relative = "editor",
        resolved = "✓",
        unresolved = "-",
        tree_type = "simple",
        toggle_tree_type = "i",
      },
      create_mr = {
        target = nil,
        template_file = nil,
        title_input = {
          width = 40,
          border = "rounded",
        },
        delete_branch = false,
        squash = false,
      },
      choose_merge_request = {
        open_reviewer = true,
      },
      info = {
        enabled = true,
        horizontal = false,
        fields = {
          "author",
          "created_at",
          "updated_at",
          "merge_status",
          "draft",
          "conflicts",
          "assignees",
          "reviewers",
          "pipeline",
          "branch",
        },
      },
      discussion_sign = {
        enabled = true,
        skip_resolved_discussion = false,
        severity = vim.diagnostic.severity.INFO,
        virtual_text = false,
        use_diagnostic_signs = true,
        priority = 100,
      },
    })
  end,
  keys = {
    { "<leader>glb", ":lua require('gitlab').choose_merge_request()<cr>", desc = "Choose MR" },
    { "<leader>glr", ":lua require('gitlab').review()<cr>", desc = "Review" },
    { "<leader>gls", ":lua require('gitlab').summary()<cr>", desc = "Summary" },
    { "<leader>glA", ":lua require('gitlab').approve()<cr>", desc = "Approve" },
    { "<leader>glR", ":lua require('gitlab').revoke()<cr>", desc = "Revoke" },
    { "<leader>glc", ":lua require('gitlab').create_comment()<cr>", desc = "Create comment" },
    {
      "<leader>glC",
      ":lua require('gitlab').create_multiline_comment()<cr>",
      desc = "Create multiline comment",
      mode = "v",
    },
    { "<leader>glO", ":lua require('gitlab').create_mr()<cr>", desc = "Create MR" },
    {
      "<leader>glm",
      ":lua require('gitlab').move_to_discussion_tree_from_diagnostic()<cr>",
      desc = "Move to discussion",
    },
    { "<leader>gln", ":lua require('gitlab').create_note()<cr>", desc = "Create note" },
    { "<leader>gld", ":lua require('gitlab').toggle_discussions()<cr>", desc = "Toggle discussions" },
    { "<leader>glaa", ":lua require('gitlab').add_assignee()<cr>", desc = "Add assignee" },
    { "<leader>glad", ":lua require('gitlab').delete_assignee()<cr>", desc = "Delete assignee" },
    { "<leader>glra", ":lua require('gitlab').add_reviewer()<cr>", desc = "Add reviewer" },
    { "<leader>glrd", ":lua require('gitlab').delete_reviewer()<cr>", desc = "Delete reviewer" },
    { "<leader>glp", ":lua require('gitlab').pipeline()<cr>", desc = "Pipeline" },
    { "<leader>glo", ":lua require('gitlab').open_in_browser()<cr>", desc = "Open in browser" },
    { "<leader>glM", ":lua require('gitlab').merge()<cr>", desc = "Merge MR" },
  },
}

